<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$brandId = $this->getRequest()->getParam('id'); 
$categorymodel = $this->getCategorymodel($brandId);
$thumbnail = $categorymodel->getData('image');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$thumbnail_path = $baseUrl.'pub/media/catalog/category/';
?>
<div class="categoryimage">
	<img src="<?php echo $thumbnail_path.$thumbnail; ?>" class="img-responsive categorypage_image" alt="<?php echo $categorymodel->getName(); ?>" alt="image"/>
</div> 